<?php

return [
    ["name" => 'zadowolony-klient-LemonTax-fin.webp', 'page_name' => "home", "order" => 1],
    ["name" => 'accountant-section-bg.webp', 'page_name' => "home", "order" => 2],
    ["name" => 'kpir-lemontax.webp', 'page_name' => "home", "order" => 3],
    ["name" => 'Wirtualne-biuro-LemonTax.webp', 'page_name' => "home", "order" => 4],
    ["name" => 'Wirtualne-biuro-LemonTax.webp', 'page_name' => "home", "order" => 5],
    ["name" => 'tablet-mockup.webp', 'page_name' => "home", "order" => 6],
    ["name" => 'Wirtualne-biuro-LemonTax.webp', 'page_name' => "home", "order" => 7],
    ["name" => 'laptop-kontakt1-lemontatx.webp', 'page_name' => "home", "order" => 8],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "about_us", "order" => 1],
    ["name" => 'Wirtualne-biuro-LemonTax.webp', 'page_name' => "about_us", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "full_accountancy", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "full_accountancy", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "ledger", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "ledger", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "registerd_lump_sum", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "registerd_lump_sum", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "hr_and_payroll", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "hr_and_payroll", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "tax_consultancy", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "tax_consultancy", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "establishment_of_the_company", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "establishment_of_the_company", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "virtual_office", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "virtual_office", "order" => 2],
    ["name" => 'strona-www-lemontax.webp', 'page_name' => "free_website", "order" => 1],
    ["name" => 'hosting-lemontax.webp', 'page_name' => "free_website", "order" => 2],
    ["name" => 'Wirtualne-biuro-LemonTax.webp', 'page_name' => "contact", "order" => 1],
];
